version: 2.1
jobs:
  build:
    working_directory: ~/circleci-demo-ruby-sinatra
    machine:
      resource_class: 2xlarge
    steps:
      - run: free

workflows:
  version: 2
  build:
    jobs:
      - build
