version: 2
jobs:
  build:
    working_directory: ~/circleci-demo-ruby-sinatra
    machine: true
    steps:
      - checkout

      # Restore bundle cache
      - restore_cache:
          key: sinatra-demo-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run: bundle install --path vendor/bundle

      # Store bundle cache
      - restore_cache:
          key: sinatra-demo-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      # Run minitest
      - run: bundle exec rake

      # Save artifacts
      - store_test_results:
          path: /tmp/test-results

workflows:
  version: 2
  build:
    jobs:
      - build
