version: 2.1

jobs:
  build-medium:
    machine:
      image: ubuntu-2004:202011-01
    resource_class: arm.medium
    steps:
      - uname -a
      - echo "Hello, Arm!"
  build-large:
    machine:
      image: ubuntu-2004:202011-01
    resource_class: arm.large
    steps:
      - uname -a
      - echo "Hello, Arm!"

workflows:
  version: 2
  build:
    jobs:
      - build-medium
      - build-large

